/*
Kafka Connect With Pulsar API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kafkaconnect

import (
	"encoding/json"
)

// checks if the WorkerStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkerStatus{}

// WorkerStatus struct for WorkerStatus
type WorkerStatus struct {
	Message *string `json:"message,omitempty"`
	Status  *string `json:"status,omitempty"`
}

// NewWorkerStatus instantiates a new WorkerStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkerStatus() *WorkerStatus {
	this := WorkerStatus{}
	return &this
}

// NewWorkerStatusWithDefaults instantiates a new WorkerStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkerStatusWithDefaults() *WorkerStatus {
	this := WorkerStatus{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *WorkerStatus) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkerStatus) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *WorkerStatus) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *WorkerStatus) SetMessage(v string) {
	o.Message = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *WorkerStatus) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkerStatus) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *WorkerStatus) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *WorkerStatus) SetStatus(v string) {
	o.Status = &v
}

func (o WorkerStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkerStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableWorkerStatus struct {
	value *WorkerStatus
	isSet bool
}

func (v NullableWorkerStatus) Get() *WorkerStatus {
	return v.value
}

func (v *NullableWorkerStatus) Set(val *WorkerStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkerStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkerStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkerStatus(val *WorkerStatus) *NullableWorkerStatus {
	return &NullableWorkerStatus{value: val, isSet: true}
}

func (v NullableWorkerStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkerStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
