// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus SelfSubjectUserReviewStatus defines the observed state of SelfSubjectUserReview
type ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus struct {
	Users []ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1UserRef `json:"users"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus instantiates a new ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus(users []ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1UserRef) *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus{}
	this.Users = users
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatusWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatusWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus{}
	return &this
}

// GetUsers returns the Users field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) GetUsers() []ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1UserRef {
	if o == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1UserRef
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) GetUsersOk() ([]ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1UserRef, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) SetUsers(v []ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1UserRef) {
	o.Users = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["users"] = o.Users
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) Get() *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) Set(val *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus(val *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SelfSubjectUserReviewStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


