//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec RoleBindingSpec defines the desired state of RoleBinding
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec struct {
	Cel *string `json:"cel,omitempty"`
	ConditionGroup *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ConditionGroup `json:"conditionGroup,omitempty"`
	RoleRef ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleRef `json:"roleRef"`
	Subjects []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Subject `json:"subjects"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec(roleRef ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleRef, subjects []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Subject) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec{}
	this.RoleRef = roleRef
	this.Subjects = subjects
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpecWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpecWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec{}
	return &this
}

// GetCel returns the Cel field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) GetCel() string {
	if o == nil || o.Cel == nil {
		var ret string
		return ret
	}
	return *o.Cel
}

// GetCelOk returns a tuple with the Cel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) GetCelOk() (*string, bool) {
	if o == nil || o.Cel == nil {
		return nil, false
	}
	return o.Cel, true
}

// HasCel returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) HasCel() bool {
	if o != nil && o.Cel != nil {
		return true
	}

	return false
}

// SetCel gets a reference to the given string and assigns it to the Cel field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) SetCel(v string) {
	o.Cel = &v
}

// GetConditionGroup returns the ConditionGroup field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) GetConditionGroup() ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ConditionGroup {
	if o == nil || o.ConditionGroup == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ConditionGroup
		return ret
	}
	return *o.ConditionGroup
}

// GetConditionGroupOk returns a tuple with the ConditionGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) GetConditionGroupOk() (*ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ConditionGroup, bool) {
	if o == nil || o.ConditionGroup == nil {
		return nil, false
	}
	return o.ConditionGroup, true
}

// HasConditionGroup returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) HasConditionGroup() bool {
	if o != nil && o.ConditionGroup != nil {
		return true
	}

	return false
}

// SetConditionGroup gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ConditionGroup and assigns it to the ConditionGroup field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) SetConditionGroup(v ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ConditionGroup) {
	o.ConditionGroup = &v
}

// GetRoleRef returns the RoleRef field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) GetRoleRef() ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleRef {
	if o == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleRef
		return ret
	}

	return o.RoleRef
}

// GetRoleRefOk returns a tuple with the RoleRef field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) GetRoleRefOk() (*ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleRef, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleRef, true
}

// SetRoleRef sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) SetRoleRef(v ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleRef) {
	o.RoleRef = v
}

// GetSubjects returns the Subjects field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) GetSubjects() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Subject {
	if o == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Subject
		return ret
	}

	return o.Subjects
}

// GetSubjectsOk returns a tuple with the Subjects field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) GetSubjectsOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Subject, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subjects, true
}

// SetSubjects sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) SetSubjects(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Subject) {
	o.Subjects = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Cel != nil {
		toSerialize["cel"] = o.Cel
	}
	if o.ConditionGroup != nil {
		toSerialize["conditionGroup"] = o.ConditionGroup
	}
	if true {
		toSerialize["roleRef"] = o.RoleRef
	}
	if true {
		toSerialize["subjects"] = o.Subjects
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


