// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec ProductSpec defines the desired state of Product
type ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec struct {
	// Description is a product description
	Description *string `json:"description,omitempty"`
	// Name is the product name.
	Name *string `json:"name,omitempty"`
	// Prices associated with the product.
	Prices []ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductPrice `json:"prices,omitempty"`
	Stripe *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripeProductSpec `json:"stripe,omitempty"`
	Suger *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProductSpec `json:"suger,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpecWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpecWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) SetDescription(v string) {
	o.Description = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) SetName(v string) {
	o.Name = &v
}

// GetPrices returns the Prices field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) GetPrices() []ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductPrice {
	if o == nil || o.Prices == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductPrice
		return ret
	}
	return o.Prices
}

// GetPricesOk returns a tuple with the Prices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) GetPricesOk() ([]ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductPrice, bool) {
	if o == nil || o.Prices == nil {
		return nil, false
	}
	return o.Prices, true
}

// HasPrices returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) HasPrices() bool {
	if o != nil && o.Prices != nil {
		return true
	}

	return false
}

// SetPrices gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductPrice and assigns it to the Prices field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) SetPrices(v []ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductPrice) {
	o.Prices = v
}

// GetStripe returns the Stripe field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) GetStripe() ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripeProductSpec {
	if o == nil || o.Stripe == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripeProductSpec
		return ret
	}
	return *o.Stripe
}

// GetStripeOk returns a tuple with the Stripe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) GetStripeOk() (*ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripeProductSpec, bool) {
	if o == nil || o.Stripe == nil {
		return nil, false
	}
	return o.Stripe, true
}

// HasStripe returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) HasStripe() bool {
	if o != nil && o.Stripe != nil {
		return true
	}

	return false
}

// SetStripe gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripeProductSpec and assigns it to the Stripe field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) SetStripe(v ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripeProductSpec) {
	o.Stripe = &v
}

// GetSuger returns the Suger field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) GetSuger() ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProductSpec {
	if o == nil || o.Suger == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProductSpec
		return ret
	}
	return *o.Suger
}

// GetSugerOk returns a tuple with the Suger field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) GetSugerOk() (*ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProductSpec, bool) {
	if o == nil || o.Suger == nil {
		return nil, false
	}
	return o.Suger, true
}

// HasSuger returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) HasSuger() bool {
	if o != nil && o.Suger != nil {
		return true
	}

	return false
}

// SetSuger gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProductSpec and assigns it to the Suger field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) SetSuger(v ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProductSpec) {
	o.Suger = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Prices != nil {
		toSerialize["prices"] = o.Prices
	}
	if o.Stripe != nil {
		toSerialize["stripe"] = o.Stripe
	}
	if o.Suger != nil {
		toSerialize["suger"] = o.Suger
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) Get() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) Set(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


