//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// V1SecretKeySelector SecretKeySelector selects a key of a Secret.
type V1SecretKeySelector struct {
	// The key of the secret to select from.  Must be a valid secret key.
	Key string `json:"key"`
	// Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
	Name *string `json:"name,omitempty"`
	// Specify whether the Secret or its key must be defined
	Optional *bool `json:"optional,omitempty"`
}

// NewV1SecretKeySelector instantiates a new V1SecretKeySelector object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SecretKeySelector(key string) *V1SecretKeySelector {
	this := V1SecretKeySelector{}
	this.Key = key
	return &this
}

// NewV1SecretKeySelectorWithDefaults instantiates a new V1SecretKeySelector object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SecretKeySelectorWithDefaults() *V1SecretKeySelector {
	this := V1SecretKeySelector{}
	return &this
}

// GetKey returns the Key field value
func (o *V1SecretKeySelector) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *V1SecretKeySelector) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *V1SecretKeySelector) SetKey(v string) {
	o.Key = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *V1SecretKeySelector) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SecretKeySelector) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *V1SecretKeySelector) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *V1SecretKeySelector) SetName(v string) {
	o.Name = &v
}

// GetOptional returns the Optional field value if set, zero value otherwise.
func (o *V1SecretKeySelector) GetOptional() bool {
	if o == nil || o.Optional == nil {
		var ret bool
		return ret
	}
	return *o.Optional
}

// GetOptionalOk returns a tuple with the Optional field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SecretKeySelector) GetOptionalOk() (*bool, bool) {
	if o == nil || o.Optional == nil {
		return nil, false
	}
	return o.Optional, true
}

// HasOptional returns a boolean if a field has been set.
func (o *V1SecretKeySelector) HasOptional() bool {
	if o != nil && o.Optional != nil {
		return true
	}

	return false
}

// SetOptional gets a reference to the given bool and assigns it to the Optional field.
func (o *V1SecretKeySelector) SetOptional(v bool) {
	o.Optional = &v
}

func (o V1SecretKeySelector) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["key"] = o.Key
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Optional != nil {
		toSerialize["optional"] = o.Optional
	}
	return json.Marshal(toSerialize)
}

type NullableV1SecretKeySelector struct {
	value *V1SecretKeySelector
	isSet bool
}

func (v NullableV1SecretKeySelector) Get() *V1SecretKeySelector {
	return v.value
}

func (v *NullableV1SecretKeySelector) Set(val *V1SecretKeySelector) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SecretKeySelector) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SecretKeySelector) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SecretKeySelector(val *V1SecretKeySelector) *NullableV1SecretKeySelector {
	return &NullableV1SecretKeySelector{value: val, isSet: true}
}

func (v NullableV1SecretKeySelector) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SecretKeySelector) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


