//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway Gateway defines the access of pulsar cluster endpoint
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway struct {
	// Access is the access type of the pulsar gateway, available values are public or private. It is immutable, with the default value public.
	Access *string `json:"access,omitempty"`
	PrivateService *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PrivateService `json:"privateService,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GatewayWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GatewayWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway{}
	return &this
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) GetAccess() string {
	if o == nil || o.Access == nil {
		var ret string
		return ret
	}
	return *o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) GetAccessOk() (*string, bool) {
	if o == nil || o.Access == nil {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) HasAccess() bool {
	if o != nil && o.Access != nil {
		return true
	}

	return false
}

// SetAccess gets a reference to the given string and assigns it to the Access field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) SetAccess(v string) {
	o.Access = &v
}

// GetPrivateService returns the PrivateService field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) GetPrivateService() ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PrivateService {
	if o == nil || o.PrivateService == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PrivateService
		return ret
	}
	return *o.PrivateService
}

// GetPrivateServiceOk returns a tuple with the PrivateService field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) GetPrivateServiceOk() (*ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PrivateService, bool) {
	if o == nil || o.PrivateService == nil {
		return nil, false
	}
	return o.PrivateService, true
}

// HasPrivateService returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) HasPrivateService() bool {
	if o != nil && o.PrivateService != nil {
		return true
	}

	return false
}

// SetPrivateService gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PrivateService and assigns it to the PrivateService field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) SetPrivateService(v ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PrivateService) {
	o.PrivateService = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Access != nil {
		toSerialize["access"] = o.Access
	}
	if o.PrivateService != nil {
		toSerialize["privateService"] = o.PrivateService
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Gateway) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


