//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws struct for ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws struct {
	RegistrationToken string `json:"registrationToken"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws(registrationToken string) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws{}
	this.RegistrationToken = registrationToken
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAwsWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAwsWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws{}
	return &this
}

// GetRegistrationToken returns the RegistrationToken field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) GetRegistrationToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistrationToken
}

// GetRegistrationTokenOk returns a tuple with the RegistrationToken field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) GetRegistrationTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistrationToken, true
}

// SetRegistrationToken sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) SetRegistrationToken(v string) {
	o.RegistrationToken = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["registrationToken"] = o.RegistrationToken
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SelfRegistrationAws) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


