// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec ClusterRoleSpec defines the desired state of ClusterRole
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec struct {
	// Permissions Designed for general permission format     SERVICE.RESOURCE.VERB
	Permissions []string `json:"permissions,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpecWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpecWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec{}
	return &this
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) GetPermissions() []string {
	if o == nil || o.Permissions == nil {
		var ret []string
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) GetPermissionsOk() ([]string, bool) {
	if o == nil || o.Permissions == nil {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) HasPermissions() bool {
	if o != nil && o.Permissions != nil {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []string and assigns it to the Permissions field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) SetPermissions(v []string) {
	o.Permissions = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Permissions != nil {
		toSerialize["permissions"] = o.Permissions
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ClusterRoleSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


