//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel struct for ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel struct {
	Name string `json:"name"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel(name string) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel{}
	this.Name = name
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannelWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannelWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel{}
	return &this
}

// GetName returns the Name field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) SetName(v string) {
	o.Name = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberPulsarSpecChannel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


