//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus IdentityPoolStatus defines the desired state of IdentityPool
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus struct {
	// Conditions is an array of current observed conditions.
	Conditions []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition `json:"conditions,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatusWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatusWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus{}
	return &this
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) GetConditions() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition {
	if o == nil || o.Conditions == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) GetConditionsOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition, bool) {
	if o == nil || o.Conditions == nil {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) HasConditions() bool {
	if o != nil && o.Conditions != nil {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition and assigns it to the Conditions field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) SetConditions(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition) {
	o.Conditions = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Conditions != nil {
		toSerialize["conditions"] = o.Conditions
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1IdentityPoolStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


