// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring struct for ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring struct {
	// Project is the Google project containing UO components.
	Project string `json:"project"`
	// VMTenant identifies the VM tenant to use (accountID or accountID:projectID).
	VmTenant string `json:"vmTenant"`
	VmagentSecretRef ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SecretReference `json:"vmagentSecretRef"`
	// VMinsertBackendServiceName identifies the backend service for vminsert.
	VminsertBackendServiceName string `json:"vminsertBackendServiceName"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring(project string, vmTenant string, vmagentSecretRef ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SecretReference, vminsertBackendServiceName string) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring{}
	this.Project = project
	this.VmTenant = vmTenant
	this.VmagentSecretRef = vmagentSecretRef
	this.VminsertBackendServiceName = vminsertBackendServiceName
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoringWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoringWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring{}
	return &this
}

// GetProject returns the Project field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) SetProject(v string) {
	o.Project = v
}

// GetVmTenant returns the VmTenant field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) GetVmTenant() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VmTenant
}

// GetVmTenantOk returns a tuple with the VmTenant field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) GetVmTenantOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VmTenant, true
}

// SetVmTenant sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) SetVmTenant(v string) {
	o.VmTenant = v
}

// GetVmagentSecretRef returns the VmagentSecretRef field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) GetVmagentSecretRef() ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SecretReference {
	if o == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SecretReference
		return ret
	}

	return o.VmagentSecretRef
}

// GetVmagentSecretRefOk returns a tuple with the VmagentSecretRef field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) GetVmagentSecretRefOk() (*ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SecretReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VmagentSecretRef, true
}

// SetVmagentSecretRef sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) SetVmagentSecretRef(v ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SecretReference) {
	o.VmagentSecretRef = v
}

// GetVminsertBackendServiceName returns the VminsertBackendServiceName field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) GetVminsertBackendServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VminsertBackendServiceName
}

// GetVminsertBackendServiceNameOk returns a tuple with the VminsertBackendServiceName field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) GetVminsertBackendServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VminsertBackendServiceName, true
}

// SetVminsertBackendServiceName sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) SetVminsertBackendServiceName(v string) {
	o.VminsertBackendServiceName = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["project"] = o.Project
	}
	if true {
		toSerialize["vmTenant"] = o.VmTenant
	}
	if true {
		toSerialize["vmagentSecretRef"] = o.VmagentSecretRef
	}
	if true {
		toSerialize["vminsertBackendServiceName"] = o.VminsertBackendServiceName
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberMonitoring) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


