// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS DNS defines the DNS domain and how should the DNS zone be managed. ID and Name must be specified at the same time
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS struct {
	// ID is the identifier of a DNS Zone. It can be AWS zone id, GCP zone name, and Azure zone id If ID is specified, an existing zone will be used. Otherwise, a new DNS zone will be created and managed by SN.
	Id *string `json:"id,omitempty"`
	// Name is the dns domain name. It can be AWS zone name, GCP dns name and Azure zone name.
	Name *string `json:"name,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNSWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNSWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) SetName(v string) {
	o.Name = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DNS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


