//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec ZooKeeperSetOptionSpec defines a reference to a Pool
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec struct {
	ZooKeeperSetRef ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetReference `json:"zooKeeperSetRef"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec(zooKeeperSetRef ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetReference) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec{}
	this.ZooKeeperSetRef = zooKeeperSetRef
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpecWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpecWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec{}
	return &this
}

// GetZooKeeperSetRef returns the ZooKeeperSetRef field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) GetZooKeeperSetRef() ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetReference {
	if o == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetReference
		return ret
	}

	return o.ZooKeeperSetRef
}

// GetZooKeeperSetRefOk returns a tuple with the ZooKeeperSetRef field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) GetZooKeeperSetRefOk() (*ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetReference, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ZooKeeperSetRef, true
}

// SetZooKeeperSetRef sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) SetZooKeeperSetRef(v ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetReference) {
	o.ZooKeeperSetRef = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["zooKeeperSetRef"] = o.ZooKeeperSetRef
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2ZooKeeperSetOptionSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


