//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain struct for ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain struct {
	Name string `json:"name"`
	Tls *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DomainTLS `json:"tls,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain(name string) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain{}
	this.Name = name
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DomainWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DomainWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain{}
	return &this
}

// GetName returns the Name field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) SetName(v string) {
	o.Name = v
}

// GetTls returns the Tls field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) GetTls() ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DomainTLS {
	if o == nil || o.Tls == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DomainTLS
		return ret
	}
	return *o.Tls
}

// GetTlsOk returns a tuple with the Tls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) GetTlsOk() (*ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DomainTLS, bool) {
	if o == nil || o.Tls == nil {
		return nil, false
	}
	return o.Tls, true
}

// HasTls returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) HasTls() bool {
	if o != nil && o.Tls != nil {
		return true
	}

	return false
}

// SetTls gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DomainTLS and assigns it to the Tls field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) SetTls(v ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1DomainTLS) {
	o.Tls = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) SetType(v string) {
	o.Type = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Tls != nil {
		toSerialize["tls"] = o.Tls
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Domain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


