//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection struct for ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection struct {
	ProjectId string `json:"projectId"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection(projectId string) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection{}
	this.ProjectId = projectId
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnectionWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnectionWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection{}
	return &this
}

// GetProjectId returns the ProjectId field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) SetProjectId(v string) {
	o.ProjectId = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["projectId"] = o.ProjectId
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


