//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct struct for ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct
type ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct struct {
	// DimensionKey is the metering dimension of the Suger product.
	DimensionKey string `json:"dimensionKey"`
	// ProductID is the suger product id.
	ProductID *string `json:"productID,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct(dimensionKey string) *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct{}
	this.DimensionKey = dimensionKey
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProductWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProductWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct{}
	return &this
}

// GetDimensionKey returns the DimensionKey field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) GetDimensionKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DimensionKey
}

// GetDimensionKeyOk returns a tuple with the DimensionKey field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) GetDimensionKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DimensionKey, true
}

// SetDimensionKey sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) SetDimensionKey(v string) {
	o.DimensionKey = v
}

// GetProductID returns the ProductID field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) GetProductID() string {
	if o == nil || o.ProductID == nil {
		var ret string
		return ret
	}
	return *o.ProductID
}

// GetProductIDOk returns a tuple with the ProductID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) GetProductIDOk() (*string, bool) {
	if o == nil || o.ProductID == nil {
		return nil, false
	}
	return o.ProductID, true
}

// HasProductID returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) HasProductID() bool {
	if o != nil && o.ProductID != nil {
		return true
	}

	return false
}

// SetProductID gets a reference to the given string and assigns it to the ProductID field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) SetProductID(v string) {
	o.ProductID = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["dimensionKey"] = o.DimensionKey
	}
	if o.ProductID != nil {
		toSerialize["productID"] = o.ProductID
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) Get() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) Set(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SugerProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


