// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference PoolMemberReference is a reference to a pool member with a given name.
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference struct {
	Name string `json:"name"`
	Namespace string `json:"namespace"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference(name string, namespace string) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference{}
	this.Name = name
	this.Namespace = namespace
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReferenceWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReferenceWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference{}
	return &this
}

// GetName returns the Name field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) SetNamespace(v string) {
	o.Namespace = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["namespace"] = o.Namespace
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2PoolMemberReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


