//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec struct for ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec struct {
	// A role chain that is provided by name through the CLI to designate which access chain to take when accessing a poolmember.
	Chains []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain `json:"chains,omitempty"`
	RoleChain []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition `json:"roleChain,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpecWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpecWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec{}
	return &this
}

// GetChains returns the Chains field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) GetChains() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain {
	if o == nil || o.Chains == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain
		return ret
	}
	return o.Chains
}

// GetChainsOk returns a tuple with the Chains field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) GetChainsOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain, bool) {
	if o == nil || o.Chains == nil {
		return nil, false
	}
	return o.Chains, true
}

// HasChains returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) HasChains() bool {
	if o != nil && o.Chains != nil {
		return true
	}

	return false
}

// SetChains gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain and assigns it to the Chains field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) SetChains(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) {
	o.Chains = v
}

// GetRoleChain returns the RoleChain field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) GetRoleChain() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition {
	if o == nil || o.RoleChain == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition
		return ret
	}
	return o.RoleChain
}

// GetRoleChainOk returns a tuple with the RoleChain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) GetRoleChainOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition, bool) {
	if o == nil || o.RoleChain == nil {
		return nil, false
	}
	return o.RoleChain, true
}

// HasRoleChain returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) HasRoleChain() bool {
	if o != nil && o.RoleChain != nil {
		return true
	}

	return false
}

// SetRoleChain gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition and assigns it to the RoleChain field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) SetRoleChain(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition) {
	o.RoleChain = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Chains != nil {
		toSerialize["chains"] = o.Chains
	}
	if o.RoleChain != nil {
		toSerialize["roleChain"] = o.RoleChain
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1SupportAccessOptionsSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


