//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec CloudConnectionSpec defines the desired state of CloudConnection
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec struct {
	Aws *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AWSCloudConnection `json:"aws,omitempty"`
	Azure *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AzureConnection `json:"azure,omitempty"`
	Gcp *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection `json:"gcp,omitempty"`
	Type string `json:"type"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec(type_ string) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec{}
	this.Type = type_
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpecWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpecWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec{}
	return &this
}

// GetAws returns the Aws field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) GetAws() ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AWSCloudConnection {
	if o == nil || o.Aws == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AWSCloudConnection
		return ret
	}
	return *o.Aws
}

// GetAwsOk returns a tuple with the Aws field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) GetAwsOk() (*ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AWSCloudConnection, bool) {
	if o == nil || o.Aws == nil {
		return nil, false
	}
	return o.Aws, true
}

// HasAws returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) HasAws() bool {
	if o != nil && o.Aws != nil {
		return true
	}

	return false
}

// SetAws gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AWSCloudConnection and assigns it to the Aws field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) SetAws(v ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AWSCloudConnection) {
	o.Aws = &v
}

// GetAzure returns the Azure field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) GetAzure() ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AzureConnection {
	if o == nil || o.Azure == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AzureConnection
		return ret
	}
	return *o.Azure
}

// GetAzureOk returns a tuple with the Azure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) GetAzureOk() (*ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AzureConnection, bool) {
	if o == nil || o.Azure == nil {
		return nil, false
	}
	return o.Azure, true
}

// HasAzure returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) HasAzure() bool {
	if o != nil && o.Azure != nil {
		return true
	}

	return false
}

// SetAzure gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AzureConnection and assigns it to the Azure field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) SetAzure(v ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1AzureConnection) {
	o.Azure = &v
}

// GetGcp returns the Gcp field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) GetGcp() ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection {
	if o == nil || o.Gcp == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection
		return ret
	}
	return *o.Gcp
}

// GetGcpOk returns a tuple with the Gcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) GetGcpOk() (*ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection, bool) {
	if o == nil || o.Gcp == nil {
		return nil, false
	}
	return o.Gcp, true
}

// HasGcp returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) HasGcp() bool {
	if o != nil && o.Gcp != nil {
		return true
	}

	return false
}

// SetGcp gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection and assigns it to the Gcp field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) SetGcp(v ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCPCloudConnection) {
	o.Gcp = &v
}

// GetType returns the Type field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) SetType(v string) {
	o.Type = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Aws != nil {
		toSerialize["aws"] = o.Aws
	}
	if o.Azure != nil {
		toSerialize["azure"] = o.Azure
	}
	if o.Gcp != nil {
		toSerialize["gcp"] = o.Gcp
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


