// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference PriceReference references a price within a Product object.
type ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference struct {
	// Key is the price key within the product specification.
	Key *string `json:"key,omitempty"`
	Product *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductReference `json:"product,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReferenceWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReferenceWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) SetKey(v string) {
	o.Key = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) GetProduct() ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductReference {
	if o == nil || o.Product == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductReference
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) GetProductOk() (*ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductReference, bool) {
	if o == nil || o.Product == nil {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) HasProduct() bool {
	if o != nil && o.Product != nil {
		return true
	}

	return false
}

// SetProduct gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductReference and assigns it to the Product field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) SetProduct(v ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductReference) {
	o.Product = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Product != nil {
		toSerialize["product"] = o.Product
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) Get() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) Set(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PriceReference) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


