//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus RoleBindingStatus defines the observed state of RoleBinding
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus struct {
	// Conditions is an array of current observed conditions.
	Conditions []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition `json:"conditions,omitempty"`
	// FailedClusters is an array of clusters which failed to apply the ClusterRole resources.
	FailedClusters []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedCluster `json:"failedClusters,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatusWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatusWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus{}
	return &this
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) GetConditions() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition {
	if o == nil || o.Conditions == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) GetConditionsOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition, bool) {
	if o == nil || o.Conditions == nil {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) HasConditions() bool {
	if o != nil && o.Conditions != nil {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition and assigns it to the Conditions field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) SetConditions(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition) {
	o.Conditions = v
}

// GetFailedClusters returns the FailedClusters field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) GetFailedClusters() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedCluster {
	if o == nil || o.FailedClusters == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedCluster
		return ret
	}
	return o.FailedClusters
}

// GetFailedClustersOk returns a tuple with the FailedClusters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) GetFailedClustersOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedCluster, bool) {
	if o == nil || o.FailedClusters == nil {
		return nil, false
	}
	return o.FailedClusters, true
}

// HasFailedClusters returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) HasFailedClusters() bool {
	if o != nil && o.FailedClusters != nil {
		return true
	}

	return false
}

// SetFailedClusters gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedCluster and assigns it to the FailedClusters field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) SetFailedClusters(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedCluster) {
	o.FailedClusters = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Conditions != nil {
		toSerialize["conditions"] = o.Conditions
	}
	if o.FailedClusters != nil {
		toSerialize["failedClusters"] = o.FailedClusters
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleBindingStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


