// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization struct for ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization
type ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization struct {
	DisplayName string `json:"displayName"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization instantiates a new ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization(displayName string) *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization {
	this := ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization{}
	this.DisplayName = displayName
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1OrganizationWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1OrganizationWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization {
	this := ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization{}
	return &this
}

// GetDisplayName returns the DisplayName field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) SetDisplayName(v string) {
	o.DisplayName = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["displayName"] = o.DisplayName
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) Get() *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) Set(val *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization(val *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Organization) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


