//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice struct for ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice
type ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice struct {
	Key *string `json:"key,omitempty"`
	StripeID *string `json:"stripeID,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPriceWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPriceWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) SetKey(v string) {
	o.Key = &v
}

// GetStripeID returns the StripeID field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) GetStripeID() string {
	if o == nil || o.StripeID == nil {
		var ret string
		return ret
	}
	return *o.StripeID
}

// GetStripeIDOk returns a tuple with the StripeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) GetStripeIDOk() (*string, bool) {
	if o == nil || o.StripeID == nil {
		return nil, false
	}
	return o.StripeID, true
}

// HasStripeID returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) HasStripeID() bool {
	if o != nil && o.StripeID != nil {
		return true
	}

	return false
}

// SetStripeID gets a reference to the given string and assigns it to the StripeID field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) SetStripeID(v string) {
	o.StripeID = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.StripeID != nil {
		toSerialize["stripeID"] = o.StripeID
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) Get() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) Set(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1ProductStatusPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


