//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem struct for ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem
type ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem struct {
	// Key is the item key within the subscription.
	Key *string `json:"key,omitempty"`
	// Product is the Product object reference as a qualified name.
	Product *string `json:"product,omitempty"`
	// The unique identifier for the Stripe subscription item.
	StripeID *string `json:"stripeID,omitempty"`
	// The unique identifier for the Suger entitlement item.
	SugerID *string `json:"sugerID,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItemWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItemWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) SetKey(v string) {
	o.Key = &v
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) GetProduct() string {
	if o == nil || o.Product == nil {
		var ret string
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) GetProductOk() (*string, bool) {
	if o == nil || o.Product == nil {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) HasProduct() bool {
	if o != nil && o.Product != nil {
		return true
	}

	return false
}

// SetProduct gets a reference to the given string and assigns it to the Product field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) SetProduct(v string) {
	o.Product = &v
}

// GetStripeID returns the StripeID field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) GetStripeID() string {
	if o == nil || o.StripeID == nil {
		var ret string
		return ret
	}
	return *o.StripeID
}

// GetStripeIDOk returns a tuple with the StripeID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) GetStripeIDOk() (*string, bool) {
	if o == nil || o.StripeID == nil {
		return nil, false
	}
	return o.StripeID, true
}

// HasStripeID returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) HasStripeID() bool {
	if o != nil && o.StripeID != nil {
		return true
	}

	return false
}

// SetStripeID gets a reference to the given string and assigns it to the StripeID field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) SetStripeID(v string) {
	o.StripeID = &v
}

// GetSugerID returns the SugerID field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) GetSugerID() string {
	if o == nil || o.SugerID == nil {
		var ret string
		return ret
	}
	return *o.SugerID
}

// GetSugerIDOk returns a tuple with the SugerID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) GetSugerIDOk() (*string, bool) {
	if o == nil || o.SugerID == nil {
		return nil, false
	}
	return o.SugerID, true
}

// HasSugerID returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) HasSugerID() bool {
	if o != nil && o.SugerID != nil {
		return true
	}

	return false
}

// SetSugerID gets a reference to the given string and assigns it to the SugerID field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) SetSugerID(v string) {
	o.SugerID = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Product != nil {
		toSerialize["product"] = o.Product
	}
	if o.StripeID != nil {
		toSerialize["stripeID"] = o.StripeID
	}
	if o.SugerID != nil {
		toSerialize["sugerID"] = o.SugerID
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) Get() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) Set(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1SubscriptionStatusSubscriptionItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


