//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus PoolMemberStatus defines the observed state of PoolMember
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus struct {
	// Conditions is an array of current observed conditions.
	Conditions []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition `json:"conditions,omitempty"`
	DeploymentType string `json:"deploymentType"`
	// InstalledCSVs shows the name and status of installed operator versions
	InstalledCSVs []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1InstalledCSV `json:"installedCSVs,omitempty"`
	// ObservedGeneration is the most recent generation observed by the PoolMember controller.
	ObservedGeneration int64 `json:"observedGeneration"`
	ServerVersion *string `json:"serverVersion,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus(deploymentType string, observedGeneration int64) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus{}
	this.DeploymentType = deploymentType
	this.ObservedGeneration = observedGeneration
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatusWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatusWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus{}
	return &this
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) GetConditions() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition {
	if o == nil || o.Conditions == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) GetConditionsOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition, bool) {
	if o == nil || o.Conditions == nil {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) HasConditions() bool {
	if o != nil && o.Conditions != nil {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition and assigns it to the Conditions field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) SetConditions(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition) {
	o.Conditions = v
}

// GetDeploymentType returns the DeploymentType field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) GetDeploymentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DeploymentType
}

// GetDeploymentTypeOk returns a tuple with the DeploymentType field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) GetDeploymentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeploymentType, true
}

// SetDeploymentType sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) SetDeploymentType(v string) {
	o.DeploymentType = v
}

// GetInstalledCSVs returns the InstalledCSVs field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) GetInstalledCSVs() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1InstalledCSV {
	if o == nil || o.InstalledCSVs == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1InstalledCSV
		return ret
	}
	return o.InstalledCSVs
}

// GetInstalledCSVsOk returns a tuple with the InstalledCSVs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) GetInstalledCSVsOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1InstalledCSV, bool) {
	if o == nil || o.InstalledCSVs == nil {
		return nil, false
	}
	return o.InstalledCSVs, true
}

// HasInstalledCSVs returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) HasInstalledCSVs() bool {
	if o != nil && o.InstalledCSVs != nil {
		return true
	}

	return false
}

// SetInstalledCSVs gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1InstalledCSV and assigns it to the InstalledCSVs field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) SetInstalledCSVs(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1InstalledCSV) {
	o.InstalledCSVs = v
}

// GetObservedGeneration returns the ObservedGeneration field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) GetObservedGeneration() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ObservedGeneration
}

// GetObservedGenerationOk returns a tuple with the ObservedGeneration field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) GetObservedGenerationOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObservedGeneration, true
}

// SetObservedGeneration sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) SetObservedGeneration(v int64) {
	o.ObservedGeneration = v
}

// GetServerVersion returns the ServerVersion field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) GetServerVersion() string {
	if o == nil || o.ServerVersion == nil {
		var ret string
		return ret
	}
	return *o.ServerVersion
}

// GetServerVersionOk returns a tuple with the ServerVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) GetServerVersionOk() (*string, bool) {
	if o == nil || o.ServerVersion == nil {
		return nil, false
	}
	return o.ServerVersion, true
}

// HasServerVersion returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) HasServerVersion() bool {
	if o != nil && o.ServerVersion != nil {
		return true
	}

	return false
}

// SetServerVersion gets a reference to the given string and assigns it to the ServerVersion field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) SetServerVersion(v string) {
	o.ServerVersion = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Conditions != nil {
		toSerialize["conditions"] = o.Conditions
	}
	if true {
		toSerialize["deploymentType"] = o.DeploymentType
	}
	if o.InstalledCSVs != nil {
		toSerialize["installedCSVs"] = o.InstalledCSVs
	}
	if true {
		toSerialize["observedGeneration"] = o.ObservedGeneration
	}
	if o.ServerVersion != nil {
		toSerialize["serverVersion"] = o.ServerVersion
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1PoolMemberStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


