//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec struct for ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec struct {
	Project string `json:"project"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec(project string) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec{}
	this.Project = project
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpecWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpecWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec{}
	return &this
}

// GetProject returns the Project field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) SetProject(v string) {
	o.Project = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["project"] = o.Project
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1GCloudOrganizationSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


