// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain Chain specifies a named chain for a role definition array.
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain struct {
	Name *string `json:"name,omitempty"`
	RoleChain []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition `json:"roleChain,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ChainWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1ChainWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) SetName(v string) {
	o.Name = &v
}

// GetRoleChain returns the RoleChain field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) GetRoleChain() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition {
	if o == nil || o.RoleChain == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition
		return ret
	}
	return o.RoleChain
}

// GetRoleChainOk returns a tuple with the RoleChain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) GetRoleChainOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition, bool) {
	if o == nil || o.RoleChain == nil {
		return nil, false
	}
	return o.RoleChain, true
}

// HasRoleChain returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) HasRoleChain() bool {
	if o != nil && o.RoleChain != nil {
		return true
	}

	return false
}

// SetRoleChain gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition and assigns it to the RoleChain field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) SetRoleChain(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RoleDefinition) {
	o.RoleChain = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.RoleChain != nil {
		toSerialize["roleChain"] = o.RoleChain
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Chain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


