//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec struct for ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec
type ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec struct {
	// Active indicates the price is active on the product
	Active *bool `json:"active,omitempty"`
	// Currency is the required three-letter ISO currency code The codes below were generated from https://stripe.com/docs/currencies
	Currency *string `json:"currency,omitempty"`
	// Name to be displayed in the Stripe dashboard, hidden from customers
	Name *string `json:"name,omitempty"`
	Recurring *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceRecurrence `json:"recurring,omitempty"`
	// Tiers are Stripes billing tiers like
	Tiers []ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1Tier `json:"tiers,omitempty"`
	// TiersMode is the stripe tier mode
	TiersMode *string `json:"tiersMode,omitempty"`
	// UnitAmount in dollars. If present, billing_scheme is assumed to be per_unit
	UnitAmount *string `json:"unitAmount,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpecWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpecWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec{}
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetActive() bool {
	if o == nil || o.Active == nil {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetActiveOk() (*bool, bool) {
	if o == nil || o.Active == nil {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) HasActive() bool {
	if o != nil && o.Active != nil {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) SetActive(v bool) {
	o.Active = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetCurrency() string {
	if o == nil || o.Currency == nil {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetCurrencyOk() (*string, bool) {
	if o == nil || o.Currency == nil {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) HasCurrency() bool {
	if o != nil && o.Currency != nil {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) SetCurrency(v string) {
	o.Currency = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) SetName(v string) {
	o.Name = &v
}

// GetRecurring returns the Recurring field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetRecurring() ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceRecurrence {
	if o == nil || o.Recurring == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceRecurrence
		return ret
	}
	return *o.Recurring
}

// GetRecurringOk returns a tuple with the Recurring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetRecurringOk() (*ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceRecurrence, bool) {
	if o == nil || o.Recurring == nil {
		return nil, false
	}
	return o.Recurring, true
}

// HasRecurring returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) HasRecurring() bool {
	if o != nil && o.Recurring != nil {
		return true
	}

	return false
}

// SetRecurring gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceRecurrence and assigns it to the Recurring field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) SetRecurring(v ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceRecurrence) {
	o.Recurring = &v
}

// GetTiers returns the Tiers field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetTiers() []ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1Tier {
	if o == nil || o.Tiers == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1Tier
		return ret
	}
	return o.Tiers
}

// GetTiersOk returns a tuple with the Tiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetTiersOk() ([]ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1Tier, bool) {
	if o == nil || o.Tiers == nil {
		return nil, false
	}
	return o.Tiers, true
}

// HasTiers returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) HasTiers() bool {
	if o != nil && o.Tiers != nil {
		return true
	}

	return false
}

// SetTiers gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1Tier and assigns it to the Tiers field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) SetTiers(v []ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1Tier) {
	o.Tiers = v
}

// GetTiersMode returns the TiersMode field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetTiersMode() string {
	if o == nil || o.TiersMode == nil {
		var ret string
		return ret
	}
	return *o.TiersMode
}

// GetTiersModeOk returns a tuple with the TiersMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetTiersModeOk() (*string, bool) {
	if o == nil || o.TiersMode == nil {
		return nil, false
	}
	return o.TiersMode, true
}

// HasTiersMode returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) HasTiersMode() bool {
	if o != nil && o.TiersMode != nil {
		return true
	}

	return false
}

// SetTiersMode gets a reference to the given string and assigns it to the TiersMode field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) SetTiersMode(v string) {
	o.TiersMode = &v
}

// GetUnitAmount returns the UnitAmount field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetUnitAmount() string {
	if o == nil || o.UnitAmount == nil {
		var ret string
		return ret
	}
	return *o.UnitAmount
}

// GetUnitAmountOk returns a tuple with the UnitAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) GetUnitAmountOk() (*string, bool) {
	if o == nil || o.UnitAmount == nil {
		return nil, false
	}
	return o.UnitAmount, true
}

// HasUnitAmount returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) HasUnitAmount() bool {
	if o != nil && o.UnitAmount != nil {
		return true
	}

	return false
}

// SetUnitAmount gets a reference to the given string and assigns it to the UnitAmount field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) SetUnitAmount(v string) {
	o.UnitAmount = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Active != nil {
		toSerialize["active"] = o.Active
	}
	if o.Currency != nil {
		toSerialize["currency"] = o.Currency
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Recurring != nil {
		toSerialize["recurring"] = o.Recurring
	}
	if o.Tiers != nil {
		toSerialize["tiers"] = o.Tiers
	}
	if o.TiersMode != nil {
		toSerialize["tiersMode"] = o.TiersMode
	}
	if o.UnitAmount != nil {
		toSerialize["unitAmount"] = o.UnitAmount
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) Get() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) Set(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePriceSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


