//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken EncryptedToken is token that is encrypted using an encryption key.
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken struct {
	// JWE is the token as a JSON Web Encryption (JWE) message. For RSA public keys, the key encryption algorithm is RSA-OAEP, and the content encryption algorithm is AES GCM.
	Jwe *string `json:"jwe,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedTokenWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedTokenWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken{}
	return &this
}

// GetJwe returns the Jwe field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) GetJwe() string {
	if o == nil || o.Jwe == nil {
		var ret string
		return ret
	}
	return *o.Jwe
}

// GetJweOk returns a tuple with the Jwe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) GetJweOk() (*string, bool) {
	if o == nil || o.Jwe == nil {
		return nil, false
	}
	return o.Jwe, true
}

// HasJwe returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) HasJwe() bool {
	if o != nil && o.Jwe != nil {
		return true
	}

	return false
}

// SetJwe gets a reference to the given string and assigns it to the Jwe field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) SetJwe(v string) {
	o.Jwe = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Jwe != nil {
		toSerialize["jwe"] = o.Jwe
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1EncryptedToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


