//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus MonitorSetStatus defines the observed state of MonitorSet
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus struct {
	// Conditions is an array of current observed conditions.
	Conditions []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2Condition `json:"conditions,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatusWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatusWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus{}
	return &this
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) GetConditions() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2Condition {
	if o == nil || o.Conditions == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2Condition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) GetConditionsOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2Condition, bool) {
	if o == nil || o.Conditions == nil {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) HasConditions() bool {
	if o != nil && o.Conditions != nil {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2Condition and assigns it to the Conditions field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) SetConditions(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2Condition) {
	o.Conditions = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Conditions != nil {
		toSerialize["conditions"] = o.Conditions
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha2MonitorSetStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


