// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding struct for ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding struct {
	// Name is the RoleBinding's name
	Name string `json:"name"`
	// Namespace is the RoleBinding's namespace
	Namespace string `json:"namespace"`
	// Reason is the failed reason
	Reason string `json:"reason"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding(name string, namespace string, reason string) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding{}
	this.Name = name
	this.Namespace = namespace
	this.Reason = reason
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBindingWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBindingWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding{}
	return &this
}

// GetName returns the Name field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) SetName(v string) {
	o.Name = v
}

// GetNamespace returns the Namespace field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) GetNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) GetNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Namespace, true
}

// SetNamespace sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) SetNamespace(v string) {
	o.Namespace = v
}

// GetReason returns the Reason field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) SetReason(v string) {
	o.Reason = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["namespace"] = o.Namespace
	}
	if true {
		toSerialize["reason"] = o.Reason
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1FailedRoleBinding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


