// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent PaymentIntent is the Schema for the paymentintents API
type ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent struct {
	// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
	ApiVersion *string `json:"apiVersion,omitempty"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
	Kind *string `json:"kind,omitempty"`
	Metadata *V1ObjectMeta `json:"metadata,omitempty"`
	Spec *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec `json:"spec,omitempty"`
	Status *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentStatus `json:"status,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent{}
	return &this
}

// GetApiVersion returns the ApiVersion field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) GetApiVersion() string {
	if o == nil || o.ApiVersion == nil {
		var ret string
		return ret
	}
	return *o.ApiVersion
}

// GetApiVersionOk returns a tuple with the ApiVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) GetApiVersionOk() (*string, bool) {
	if o == nil || o.ApiVersion == nil {
		return nil, false
	}
	return o.ApiVersion, true
}

// HasApiVersion returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) HasApiVersion() bool {
	if o != nil && o.ApiVersion != nil {
		return true
	}

	return false
}

// SetApiVersion gets a reference to the given string and assigns it to the ApiVersion field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) SetApiVersion(v string) {
	o.ApiVersion = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) GetKind() string {
	if o == nil || o.Kind == nil {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) GetKindOk() (*string, bool) {
	if o == nil || o.Kind == nil {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) HasKind() bool {
	if o != nil && o.Kind != nil {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) SetKind(v string) {
	o.Kind = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) GetMetadata() V1ObjectMeta {
	if o == nil || o.Metadata == nil {
		var ret V1ObjectMeta
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) GetMetadataOk() (*V1ObjectMeta, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given V1ObjectMeta and assigns it to the Metadata field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) SetMetadata(v V1ObjectMeta) {
	o.Metadata = &v
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) GetSpec() ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec {
	if o == nil || o.Spec == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) GetSpecOk() (*ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec and assigns it to the Spec field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) SetSpec(v ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) {
	o.Spec = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) GetStatus() ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentStatus {
	if o == nil || o.Status == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) GetStatusOk() (*ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentStatus, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentStatus and assigns it to the Status field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) SetStatus(v ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentStatus) {
	o.Status = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiVersion != nil {
		toSerialize["apiVersion"] = o.ApiVersion
	}
	if o.Kind != nil {
		toSerialize["kind"] = o.Kind
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) Get() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) Set(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


