//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
	"time"
)

// ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition Condition represents an observation of an object's state. Conditions are an extension mechanism intended to be used when the details of an observation are not a priori known or would not apply to all instances of a given Kind.  Conditions should be added to explicitly convey properties that users and components care about rather than requiring those properties to be inferred from other observations. Once defined, the meaning of a Condition can not be changed arbitrarily - it becomes part of the API, and has the same backwards- and forwards-compatibility concerns of any other part of the API.
type ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition struct {
	// Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`
	Message *string `json:"message,omitempty"`
	Reason *string `json:"reason,omitempty"`
	Status string `json:"status"`
	Type string `json:"type"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition instantiates a new ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition(status string, type_ string) *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition {
	this := ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition{}
	this.Status = status
	this.Type = type_
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1ConditionWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1ConditionWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition {
	this := ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition{}
	return &this
}

// GetLastTransitionTime returns the LastTransitionTime field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) GetLastTransitionTime() time.Time {
	if o == nil || o.LastTransitionTime == nil {
		var ret time.Time
		return ret
	}
	return *o.LastTransitionTime
}

// GetLastTransitionTimeOk returns a tuple with the LastTransitionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) GetLastTransitionTimeOk() (*time.Time, bool) {
	if o == nil || o.LastTransitionTime == nil {
		return nil, false
	}
	return o.LastTransitionTime, true
}

// HasLastTransitionTime returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) HasLastTransitionTime() bool {
	if o != nil && o.LastTransitionTime != nil {
		return true
	}

	return false
}

// SetLastTransitionTime gets a reference to the given time.Time and assigns it to the LastTransitionTime field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) SetLastTransitionTime(v time.Time) {
	o.LastTransitionTime = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) SetMessage(v string) {
	o.Message = &v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) GetReason() string {
	if o == nil || o.Reason == nil {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) GetReasonOk() (*string, bool) {
	if o == nil || o.Reason == nil {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) HasReason() bool {
	if o != nil && o.Reason != nil {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) SetReason(v string) {
	o.Reason = &v
}

// GetStatus returns the Status field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) SetStatus(v string) {
	o.Status = v
}

// GetType returns the Type field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) SetType(v string) {
	o.Type = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.LastTransitionTime != nil {
		toSerialize["lastTransitionTime"] = o.LastTransitionTime
	}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.Reason != nil {
		toSerialize["reason"] = o.Reason
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) Get() *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) Set(val *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition(val *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1Condition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


