// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
	"time"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation struct for ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation struct {
	// Decision indicates the user's response to the invitation
	Decision string `json:"decision"`
	// Expiration indicates when the invitation expires
	Expiration time.Time `json:"expiration"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation(decision string, expiration time.Time) *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation{}
	this.Decision = decision
	this.Expiration = expiration
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1InvitationWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1InvitationWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation{}
	return &this
}

// GetDecision returns the Decision field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) GetDecision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Decision
}

// GetDecisionOk returns a tuple with the Decision field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) GetDecisionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Decision, true
}

// SetDecision sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) SetDecision(v string) {
	o.Decision = v
}

// GetExpiration returns the Expiration field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) GetExpiration() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) GetExpirationOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expiration, true
}

// SetExpiration sets field value
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) SetExpiration(v time.Time) {
	o.Expiration = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["decision"] = o.Decision
	}
	if true {
		toSerialize["expiration"] = o.Expiration
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Invitation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


