//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec struct for ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec
type ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec struct {
	Namespace *string `json:"namespace,omitempty"`
	// User is the user you're testing for.
	User *string `json:"user,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec instantiates a new ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec() *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpecWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpecWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec{}
	return &this
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) SetNamespace(v string) {
	o.Namespace = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) GetUser() string {
	if o == nil || o.User == nil {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) GetUserOk() (*string, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) SetUser(v string) {
	o.User = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Namespace != nil {
		toSerialize["namespace"] = o.Namespace
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) Get() *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) Set(val *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec(val *ComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisAuthorizationV1alpha1SubjectRulesReviewSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


