//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec PaymentIntentSpec defines the desired state of PaymentIntent
type ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec struct {
	Stripe *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePaymentIntent `json:"stripe,omitempty"`
	SubscriptionName *string `json:"subscriptionName,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpecWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpecWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec {
	this := ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec{}
	return &this
}

// GetStripe returns the Stripe field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) GetStripe() ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePaymentIntent {
	if o == nil || o.Stripe == nil {
		var ret ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePaymentIntent
		return ret
	}
	return *o.Stripe
}

// GetStripeOk returns a tuple with the Stripe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) GetStripeOk() (*ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePaymentIntent, bool) {
	if o == nil || o.Stripe == nil {
		return nil, false
	}
	return o.Stripe, true
}

// HasStripe returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) HasStripe() bool {
	if o != nil && o.Stripe != nil {
		return true
	}

	return false
}

// SetStripe gets a reference to the given ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePaymentIntent and assigns it to the Stripe field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) SetStripe(v ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1StripePaymentIntent) {
	o.Stripe = &v
}

// GetSubscriptionName returns the SubscriptionName field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) GetSubscriptionName() string {
	if o == nil || o.SubscriptionName == nil {
		var ret string
		return ret
	}
	return *o.SubscriptionName
}

// GetSubscriptionNameOk returns a tuple with the SubscriptionName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) GetSubscriptionNameOk() (*string, bool) {
	if o == nil || o.SubscriptionName == nil {
		return nil, false
	}
	return o.SubscriptionName, true
}

// HasSubscriptionName returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) HasSubscriptionName() bool {
	if o != nil && o.SubscriptionName != nil {
		return true
	}

	return false
}

// SetSubscriptionName gets a reference to the given string and assigns it to the SubscriptionName field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) SetSubscriptionName(v string) {
	o.SubscriptionName = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) SetType(v string) {
	o.Type = &v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Stripe != nil {
		toSerialize["stripe"] = o.Stripe
	}
	if o.SubscriptionName != nil {
		toSerialize["subscriptionName"] = o.SubscriptionName
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) Get() *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) Set(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec(val *ComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisBillingV1alpha1PaymentIntentSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


