//
// Copyright © 2023-2024 StreamNative Inc.
//

/*
Api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sncloud

import (
	"encoding/json"
)

// ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus CloudConnectionStatus defines the observed state of CloudConnection
type ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus struct {
	AvailableLocations []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RegionInfo `json:"availableLocations,omitempty"`
	AwsPolicyVersion *string `json:"awsPolicyVersion,omitempty"`
	// Conditions is an array of current observed conditions.
	Conditions []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition `json:"conditions,omitempty"`
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus{}
	return &this
}

// NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatusWithDefaults instantiates a new ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatusWithDefaults() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus {
	this := ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus{}
	return &this
}

// GetAvailableLocations returns the AvailableLocations field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) GetAvailableLocations() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RegionInfo {
	if o == nil || o.AvailableLocations == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RegionInfo
		return ret
	}
	return o.AvailableLocations
}

// GetAvailableLocationsOk returns a tuple with the AvailableLocations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) GetAvailableLocationsOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RegionInfo, bool) {
	if o == nil || o.AvailableLocations == nil {
		return nil, false
	}
	return o.AvailableLocations, true
}

// HasAvailableLocations returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) HasAvailableLocations() bool {
	if o != nil && o.AvailableLocations != nil {
		return true
	}

	return false
}

// SetAvailableLocations gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RegionInfo and assigns it to the AvailableLocations field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) SetAvailableLocations(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1RegionInfo) {
	o.AvailableLocations = v
}

// GetAwsPolicyVersion returns the AwsPolicyVersion field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) GetAwsPolicyVersion() string {
	if o == nil || o.AwsPolicyVersion == nil {
		var ret string
		return ret
	}
	return *o.AwsPolicyVersion
}

// GetAwsPolicyVersionOk returns a tuple with the AwsPolicyVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) GetAwsPolicyVersionOk() (*string, bool) {
	if o == nil || o.AwsPolicyVersion == nil {
		return nil, false
	}
	return o.AwsPolicyVersion, true
}

// HasAwsPolicyVersion returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) HasAwsPolicyVersion() bool {
	if o != nil && o.AwsPolicyVersion != nil {
		return true
	}

	return false
}

// SetAwsPolicyVersion gets a reference to the given string and assigns it to the AwsPolicyVersion field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) SetAwsPolicyVersion(v string) {
	o.AwsPolicyVersion = &v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) GetConditions() []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition {
	if o == nil || o.Conditions == nil {
		var ret []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) GetConditionsOk() ([]ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition, bool) {
	if o == nil || o.Conditions == nil {
		return nil, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) HasConditions() bool {
	if o != nil && o.Conditions != nil {
		return true
	}

	return false
}

// SetConditions gets a reference to the given []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition and assigns it to the Conditions field.
func (o *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) SetConditions(v []ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1Condition) {
	o.Conditions = v
}

func (o ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AvailableLocations != nil {
		toSerialize["availableLocations"] = o.AvailableLocations
	}
	if o.AwsPolicyVersion != nil {
		toSerialize["awsPolicyVersion"] = o.AwsPolicyVersion
	}
	if o.Conditions != nil {
		toSerialize["conditions"] = o.Conditions
	}
	return json.Marshal(toSerialize)
}

type NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus struct {
	value *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus
	isSet bool
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) Get() *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus {
	return v.value
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) Set(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus(val *ComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus {
	return &NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus{value: val, isSet: true}
}

func (v NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComGithubStreamnativeCloudApiServerPkgApisCloudV1alpha1CloudConnectionStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


